### ISSUE TITLE
commit 116dd01b94258bd0243ab20f5467242aa834cda9 windows error

### ISSUE THREAD

**Issue by danieljpb** [uwerat/qskinny#69] opened 2018-11-06 16:01 UTC
the commit  "including the margins to heightForWidth/widthForHeight calculations"  make the elements of layouts not positioning correctly in windows, the element get the margin of the parent layout.

![error](https://user-images.githubusercontent.com/3197644/48076295-318ec280-e1e5-11e8-96a2-be7cca01fa38.png)

![ok](https://user-images.githubusercontent.com/3197644/48076296-318ec280-e1e5-11e8-9528-f437fa69b137.png)

**Comment by uwerat** [comment] 2018-11-06 16:16
The commit looks good to me - at least from looking at it briefly.
Can you send me a small demo application showing the problem, so I can debug, what is going on ? ( You can use my private Email account if you like )

**Comment by danieljpb** [comment] 2018-11-07 08:49
I have used the layout example to show like I have done, The problem seem to be when I use the QskPushButton, the QskTextLabel works (the bin directory has the windows exe)

[examples.zip](https://github.com/uwerat/qskinny/files/2556671/examples.zip)

**Comment by uwerat** [comment] 2018-11-08 08:12
The problem is related to the specific siuation, where all children of a layout have a Fixed SizePolicy ( = don't want to be larger ) and the layout has to decide, what to do with the extra space.
This code ( QskLinearBox::alignedLayoutRect ) accidentally was using heightForWidth/widthForHint for a rectangle, that is already without the margins. Instead QLayoutEngine::heightForWidth/widthForHeight has to be used.

Or in other words: fixed with the latest commit, please let me know if it works for you.

**Comment by danieljpb** [comment] 2018-11-08 09:31
Perfect!!! now works fine

Thanks so much

**Closed** 2018-11-08 16:43 UTC
